### ISSUE TITLE
'Simple bloc flutter' app are not valid

### ISSUE THREAD

**Issue by djKooks** [brianegan/flutter_architecture_samples#148]
Hello~
I'm trying to run 'simple bloc flutter' application via Android studio, but faced on error:
```
...
I/flutter (17017): dependencies: [_TodosBlocProvider], state: HomeScreenState#6a78b):
I/flutter (17017): The method 'login' was called on null.
I/flutter (17017): Receiver: null
I/flutter (17017): Tried calling: login()
I/flutter (17017): 
I/flutter (17017): When the exception was thrown, this was the stack:
I/flutter (17017): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
I/flutter (17017): #1      UserBloc.login (package:simple_blocs/src/user_bloc.dart:14:19)
I/flutter (17017): #2      HomeScreenState.build (package:simple_bloc_flutter_sample/screens/home_screen.dart:59:25)
I/flutter (17017): #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:3825:27)
...
```
Does anyone knows about this?

**Comment by mmcc007** [comment]
try:
```
flutter run -t lib/main_local_storage.dart
```

**Comment by djKooks** [comment]
@mmcc007 thanks~
