### ISSUE TITLE
How to run integration_tests?

### ISSUE THREAD

**Issue by ValeriusGC** [brianegan/flutter_architecture_samples#94]
Hi, i have no idea how to force them work?
I try to launch them inside subprojects, i.e. `vanilla`, `inherited_widget` 
when with `todo_app_test.dart` i get errors:

```
00:00 +0: Todo App Test (setUpAll)
00:00 +0 -1: Todo App Test (setUpAll) [E]
  DriverError: Could not determine URL to connect to application.
  Either the VM_SERVICE_URL environment variable should be set, or an explicit
  URL should be provided to the FlutterDriver.connect() method.
  Original error: null
  Original stack trace:
  null
  package:flutter_driver/src/driver/driver.dart 227:7           FlutterDriver.connect

... so on so forth ...

00:00 +0 -1: Todo App Test (tearDownAll)
00:00 +0 -1: Some tests failed.

Unhandled exception:
Dummy exception to set exit code.
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:391:30)
#4      _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

Process finished with exit code 255

```

when with `todo_app.dart` 

```
/home/valerius/DevTools/Flutter/bin/cache/dart-sdk/bin/dart --enable-asserts --enable-vm-service:46443 /home/valerius/DevProj/Android/Samples/Master/flutter_architecture_samples/example/inherited_widget/test_driver/todo_app.dart
Observatory listening on http://127.0.0.1:46443/

file:///home/valerius/DevTools/Flutter/packages/flutter/lib/src/material/animated_icons.dart:9:8: Error: Not found: 'dart:ui'
import 'dart:ui' as ui show Paint, Path, Canvas;
       ^
file:///home/valerius/DevTools/Flutter/packages/flutter/lib/src/material/animated_icons.dart:10:8: Error: Not found: 'dart:ui'
import 'dart:ui' show lerpDouble;
```

**Comment by mmcc007** [comment]
Integration tests have currently only been tested on emulators. So, assuming your have an emulator installed, start one emulator and run an integration test. 

For example, for a list of emulators:
```
$ flutter emulators
3 available emulators:

Nexus_5X_API_27     • Nexus 5X      • Google • Nexus 5X API 27
Nexus_6P_API_27     • Nexus 6P      • Google • Nexus 6P API 27
apple_ios_simulator • iOS Simulator • Apple
$
```
Check to see if an emulator or device is running:
```
$ flutter devices
No devices detected.

Run 'flutter emulators' to list and start any available device emulators.

Or, if you expected your device to be detected, please run "flutter doctor" to diagnose potential issues, or visit https://flutter.io/setup/ for
troubleshooting tips.
$
```
Start one emulator
```
$ flutter emulator --launch Nexus_5X_API_27
$
```
Check only one emulator running (and no devices)
```
$ flutter devices
1 connected device:

Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)
$
```
Select a project and get packages
```
$ cd example/vanilla
$ flutter packages get
Running "flutter packages get" in vanilla...                 2.3s
$
```
Run the integration test
```
$ flutter driver test_driver/todo_app.dart
Using device Android SDK built for x86.
Starting application: test_driver/todo_app.dart
Initializing gradle...                                       1.1s
Resolving dependencies...                                    3.2s
Installing build/app/outputs/apk/app.apk...                  6.0s
Gradle task 'assembleDebug'...
Gradle task 'assembleDebug'... Done                         43.7s
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                  6.6s
I/flutter (15460): Observatory listening on http://127.0.0.1:60744/
00:00 +0: Todo App Test (setUpAll)
[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:64774/
[trace] FlutterDriver: Isolate found with number: 230830484
[trace] FlutterDriver: Isolate is paused at start.
[trace] FlutterDriver: Attempting to resume isolate
[trace] FlutterDriver: Waiting for service extension
[info ] FlutterDriver: Connected to Flutter application.
00:01 +0: Todo App Test should show a loading screen while the todos are fetched
00:02 +1: Todo App Test should start with a list of Todos
00:05 +2: Todo App Test should be able to click on an item to see details
00:07 +3: Todo App Test should be able to delete a todo on the details screen
00:08 +4: Todo App Test should filter to completed todos
00:09 +5: Todo App Test should filter to active todos
00:10 +6: Todo App Test should once again filter to all todos
00:10 +7: Todo App Test should be able to view stats
00:11 +8: Todo App Test should be able to toggle a todo complete
00:12 +9: Todo App Test should be able to clear the completed todos
00:13 +10: Todo App Test should be able to toggle all todos complete
00:14 +11: Todo App Test should be able to add a todo
00:16 +12: Todo App Test should be able to modify a todo
00:19 +13: Todo App Test (tearDownAll)
00:19 +13: All tests passed!
Stopping application instance.
```

If you feel adventurous your can try running the integration test on ALL the apps.
From the root of the repo:
```
$ ./scripts/ci.sh --driver
...
```

**Comment by mmcc007** [comment]
Running from Android Studio requires a little more setup. I wrote a how-to on doing this:
https://medium.com/flutter-community/hot-reload-for-flutter-integration-tests-e0478b63bd54
