### ISSUE TITLE
Guide to project setup

### ISSUE THREAD

**Issue by Coder-Dan** [brianegan/flutter_architecture_samples#95]
I'm new to Flutter so I may have missed thing while reading the code. I ran the flutter app in the VS Code debugger, trying to understand how to one of the examples runs, in this case `bloc_flutter` example but couldn't get it to run.

I tried running the main.dart of the file within the example folder as my attempt to get it running.

I got these errors:

```
Running "flutter packages get" in bloc_flutter...               46.1s
Launching lib\main.dart on SM G9600 in debug mode...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Note: E:\Flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.5.19\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: E:\Flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.5.19\android\src\main\java\io\flutter\plugins\firebaseauth\FirebaseAuthPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: E:\Flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.2.5+1\android\src\main\java\io\flutter\plugins\firebase\core\FirebaseCorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: E:\Flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.7.4\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Warning: The rule `-keep public class *extends java.lang.annotation.Annotation {
  *;
}` uses extends but actually matches implements.
Built build\app\outputs\apk\debug\app-debug.apk.
E/FirebaseInstanceId(27790): Token retrieval failed: INVALID_SENDER
Unhandled exception:
NoSuchMethodError: The getter 'className' was called on null.
Receiver: null
Tried calling: className
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      serializeProcedure (package:front_end/src/fasta/kernel/utils.dart:99:29)
#2      FrontendCompiler.compileExpression (package:vm/frontend_server.dart:482:16)
<asynchronous suspension>
#3      _FlutterFrontendCompiler.compileExpression (package:frontend_server/server.dart:62:22)
#4      listenAndCompile.<anonymous closure> (package:vm/frontend_server.dart:797:20)
<asynchronous suspension>
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#8      _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#9      _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#10     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#11     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154:13)
#12     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129:5)
#13     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189:5)
#14     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#15     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#18     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#19     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#20     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#21     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273:7)
#22     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348:20)
#23     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)
#24     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
#25     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#26     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#28     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#29     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#30     _StreamController._add (dart:async/stream_controller.dart:639:7)
#31     _StreamController.add (dart:async/stream_controller.dart:585:5)
#32     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1721:41)
#33     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#34     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#35     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#36     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#37     _StreamController._add (dart:async/stream_controller.dart:639:7)
#38     _StreamController.add (dart:async/stream_controller.dart:585:5)
#39     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1283:33)
#40     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:826:14)
#41     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#42     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#43     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#44     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
E/FirebaseInstanceId(27790): Token retrieval failed: INVALID_SENDER
E/FirebaseInstanceId(27790): Token retrieval failed: INVALID_SENDER
E/FirebaseInstanceId(27790): Token retrieval failed: INVALID_SENDER
E/FirebaseInstanceId(27790): Token retrieval failed: INVALID_SENDER
Error -32601 received from application: Method not found
Application finished.
Exited (sigint)
```

I was hoping that you could help me out with this. I'm not sure where to add the Token in question in the last part of the error logs. VS Code may have run from workspace folder root instead of the subfolder.

**Comment by Coder-Dan** [comment]
I was able to run it if I switched to configuration to point to `lib/main_local_storage.dart` instead. Configuration for using VS Code.
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Flutter: Bloc Flutter",
            "request": "launch",
            "type": "dart",
            "program": "${workspaceFolder}/example/bloc_flutter/lib/main_local_storage.dart"
        }
    ]
}
```

I am curious as to if I have run examples properly though. Its a bit annoying that VS Code is giving errors like these, even though I know material.dart is been included.

![image](https://user-images.githubusercontent.com/17520612/50429503-f2dad600-0912-11e9-8d44-1ba5febcf482.png)

Is there a way I can fix this?

**Comment by giolin** [comment]
Have the same problem here. I am using Android Studio and it doesn't seem to work.

Is there a simple tutorial for opening and run the projects.

**Comment by mmcc007** [comment]
bloc_flutter is a bit unusual in that, to simplify testing, the main.dart expects to be called from either:
```
flutter run main_firebase.dart
```
or
```
flutter run main_firebase.dart
```
Calling from main_firebase.dart requires configuring for firebase. So should be familiar with how to configure flutter for firebase to use this option.

To create a standalone todo project for a given architecture there is a related command line utility called [flown](https://github.com/mmcc007/flown). flown will create a new todo project for the selected architecture and pull in all the necessary local packages. So is a good way to get started with any of the architectures for this todo app.

**Comment by mzj** [comment]
Is there any complete beginner friendly tutorial on how to run examples in android studio? Or at least how to build/run that "flown" tool

Step by step please, I'm totally new to flutter/dart.

**Comment by brianegan** [comment]
Thanks for the feedback, everyone! Definitely seems like we're missing something here. I'll add directions to the READMEs of each project on how to get each one running.

**Comment by brianegan** [comment]
I've renamed the `main_local_storage` to `main` to make life easier! I also need to add a few write-ups still, but hopefully that's a separate issue :)
